/* auto-generated by NAPI-RS */
/* eslint-disable */
/** module registration is done by the runtime, no need to explicitly do it now. */
export declare function fibonacci(n: number): number

/**
 * use `Fn`, `FnMut` or `FnOnce` traits to defined JavaScript callbacks
 * the return type of callbacks can only be `Result`.
 */
export declare function getCwd(callback: (arg0: string) => void): void

/** or, define the callback signature in where clause */
export declare function testCallback(callback: (arg0: string) => void): void
