/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Options for `compileTypst`. */
export interface CompileOptions {
  /** Strip everything outside `<body>…</body>` (no `<!DOCTYPE>`, `<html>`, `<head>`). */
  bodyOnly?: boolean
  /** Pretty-print the HTML output with indentation. */
  pretty?: boolean
  /** Skip metadata extraction (faster, no `<meta>` query). */
  noMetadata?: boolean
  /** Label to query for metadata. Defaults to `"meta"`. */
  metadataLabel?: string
  /** Additional directories to scan for fonts (can be repeated). */
  fontPaths?: Array<string>
}

/**
 * Result of a successful compilation.
 *
 * `metadata` is a JSON-encoded string (e.g. `'{"title":"..."}'`).
 * It is `null` when no `<meta>` label is present in the document,
 * or when `noMetadata: true` is passed. Call `JSON.parse(result.metadata)`
 * on the JS side if you need an object.
 */
export interface CompileResult {
  html: string
  metadata?: string
  warnings: Array<CompileWarning>
}

/**
 * Compile a Typst source file to HTML and extract metadata.
 *
 * The compilation runs on a worker thread; this function returns a Promise
 * so the Node.js event loop is never blocked. `input` is the path to a
 * `.typ` file on disk; the file's parent directory becomes the project
 * root for `#import` resolution.
 */
export declare function compileTypst(input: string, options?: CompileOptions | undefined | null): Promise<CompileResult>

/** A single Typst warning emitted during compilation. */
export interface CompileWarning {
  message: string
}
